services:
  app:
    container_name: templr
    image: ghcr.io/chiggy-playz/templr:latest
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
       

  db:
    container_name: templr-db
    image: postgres:15
    environment:
      - POSTGRES_DB=templr
      - POSTGRES_USER=templr
      - POSTGRES_PASSWORD=templr
    volumes:
      - templr-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "templr"]
      interval: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  templr-db-data:
